// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/analyses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all analyses. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all analyses (admin)",
                "responses": {
                    "200": {
                        "description": "Analyses array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/model": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns current active model (from override or config) and list of available model IDs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get active LLM model and available models (admin)",
                "responses": {
                    "200": {
                        "description": "active, available in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Override the active model for all LLM calls. Use a value from GET /admin/model available list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Set active LLM model (admin)",
                "parameters": [
                    {
                        "description": "Model ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_admin.SetModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "active model in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid body",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/role/{user_id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Set user role to user or admin. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update user role (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_admin.UpdateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Role updated",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all sessions. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all sessions (admin)",
                "responses": {
                    "200": {
                        "description": "Sessions array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/usage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns token usage rows. Optional query: user_id, session_id to filter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List token usage (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by session ID",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token usage array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/usage/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns aggregated token usage for gauging and manual model switching.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Token usage summary by user/session/model (admin)",
                "responses": {
                    "200": {
                        "description": "Usage summary array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/user/{user_id}/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates the user; they can be permanently removed after 90 days. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Soft delete a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User soft-deleted",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/user/{user_id}/hard-delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes the user and all associated data. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Permanently delete a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all users. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all users (admin)",
                "responses": {
                    "200": {
                        "description": "Users array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Admin required",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/auth/github": {
            "get": {
                "description": "Redirects the user to GitHub sign-in. On success they are sent to the callback URL.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start GitHub OAuth",
                "responses": {
                    "302": {
                        "description": "Redirect to GitHub"
                    }
                }
            }
        },
        "/auth/github/callback": {
            "get": {
                "description": "Handles the redirect from GitHub with the authorization code. Exchanges code for user info, finds or creates user, then redirects to frontend with token.",
                "tags": [
                    "auth"
                ],
                "summary": "GitHub OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from GitHub",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "State (optional)",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to frontend with token in query"
                    },
                    "400": {
                        "description": "Missing code or exchange failed",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/auth/google": {
            "get": {
                "description": "Redirects the user to Google sign-in. On success they are sent to the callback URL.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start Google OAuth",
                "responses": {
                    "302": {
                        "description": "Redirect to Google"
                    }
                }
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Handles the redirect from Google with the authorization code. Exchanges code for user info, finds or creates user, then redirects to frontend with token.",
                "tags": [
                    "auth"
                ],
                "summary": "Google OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Google",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "State (optional)",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to frontend with token in query"
                    },
                    "400": {
                        "description": "Missing code or exchange failed",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate with email and password. Returns JWT. Email must be verified for email provider.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_auth.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token in data.token",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or email not verified",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates the current JWT so it cannot be used again. Client should discard the token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "200": {
                        "description": "Logged out",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register with email, full name, and password. A verification code is sent by email; user must verify before login. OAuth (Google/GitHub) users are auto-verified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user (manual / email)",
                "parameters": [
                    {
                        "description": "Registration data (email, full_name, password)",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_auth.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered, verify email",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Validation or email already in use",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/auth/resend-otp": {
            "post": {
                "description": "Resend a new verification code for a manual (email) account that is not yet verified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Resend email verification code",
                "parameters": [
                    {
                        "description": "Email to resend verification code to",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_auth.ResendVerificationInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verification code resent",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Validation or resend not allowed",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/auth/verify-email": {
            "post": {
                "description": "Confirm email with the code sent after registration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "description": "Email and 6-digit code",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_auth.VerifyEmailInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email verified",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid or expired code",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all sessions for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "List my sessions",
                "responses": {
                    "200": {
                        "description": "Sessions array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new hackathon session for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Create a session",
                "parameters": [
                    {
                        "description": "Session name",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_session.CreateSessionInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Session in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a single session by ID (must belong to the user).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a session by ID (must belong to the user).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Delete a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session deleted",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update session name. Must belong to the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Update a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Name to set",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_session.PatchSessionInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated session in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/analyses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all analyses run for the session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analysis"
                ],
                "summary": "List analyses for a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analyses array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/analysis/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns latest analysis, default directive, and custom directives for the session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analysis"
                ],
                "summary": "Get analysis summary with directive for a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "AnalysisSummary in data (latest_analysis, default_directive, custom_directives)",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/analyze": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Analyzes session sources and stores structured results plus a default directive. Optional body: directives (strings) to steer the analysis and assistant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analysis"
                ],
                "summary": "Run analysis on a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Optional directives",
                        "name": "input",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/domains_analysis.AnalyzeInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Analysis in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Analysis failed",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/chat": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all chat messages (user and assistant) for the session, ordered by creation time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get chat history for a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Messages array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Send a message in a session. Uses session context and directive. Returns assistant reply.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Send a chat message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message content",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_chat.ChatInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Assistant message in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Validation or guardrail",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/chunks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all chunks (with content and summary) for the session, used for analysis context.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List chunks for a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chunks array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/sources": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all sources (URLs) added to the session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List sources for a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sources array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add winning-strategy links and the subject hackathon URL. Scraping and processing run asynchronously. Provide at least one of links or subject_link.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Add sources to a session (batch)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "links (winning strategies), subject_link (hackathon to compete in)",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains_source.AddSourcesInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Sources array in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "User in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/users/me/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates/revokes access; user details are retained.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Soft delete own account",
                "responses": {
                    "200": {
                        "description": "Account soft-deleted",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a user by ID. Authenticated users only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User in data",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/hackbuddy-backend_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domains_admin.SetModelRequest": {
            "type": "object",
            "required": [
                "model"
            ],
            "properties": {
                "model": {
                    "type": "string"
                }
            }
        },
        "domains_admin.UpdateRoleRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ]
                }
            }
        },
        "domains_analysis.AnalyzeInput": {
            "type": "object",
            "properties": {
                "directives": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domains_auth.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domains_auth.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "full_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "domains_auth.ResendVerificationInput": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "domains_auth.VerifyEmailInput": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "domains_chat.ChatInput": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "domains_session.CreateSessionInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "domains_session.PatchSessionInput": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "domains_source.AddSourcesInput": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subject_link": {
                    "type": "string"
                }
            }
        },
        "hackbuddy-backend_pkg_response.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "{} | [] | null"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "description": "\"success\" | \"error\"",
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://hackbuddy-im66.onrender.com",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hackathon Intelligence Platform API",
	Description:      "Production-grade Go backend for Hackathon Intelligence.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
